services:
  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules
            - server
    depends_on:
      - backend
    networks:
      - frontend
  backend:
    build:
      context: ./server
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules
    depends_on:
      - database
    networks:
      - frontend
      - backend
  database:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - backend
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
volumes:
  redis_data:
networks:
  frontend:
  backend:
