services:
  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules
            - server
        - action: rebuild
          path: package.json
    depends_on:
      - backend
    networks:
      - frontend
  backend:
    build:
      context: ./server
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules
    depends_on:
      - database
    networks:
      - frontend
      - backend
  database:
    image: redis/redis-stack:latest
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - backend
    volumes:
      - redis_data:/data
volumes:
  redis_data:
networks:
  frontend:
  backend:
